# Generated by Django 4.2.1 on 2024-10-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categories_products_remove_item_categroy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categroy',
            new_name='category',
        ),
    ]
